dist: trusty
sudo: false

language: go

go:
  - 1.7

env:
  - GOMAXPROCS=7

# branches:
#   only:
#     - master

env:
  - CONSUL_VERSION=0.7.2

before_install:
  - curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul.zip
  - mkdir ~/bin
  - mv consul ~/bin
  - export PATH="~/bin:$PATH"

script: make test test-race integration
